# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = kwayland

HEADERS = \
   $$PWD/autotests/client/test_xdg_shell.h \
   $$PWD/src/client/appmenu.h \
   $$PWD/src/client/blur.h \
   $$PWD/src/client/buffer.h \
   $$PWD/src/client/buffer_p.h \
   $$PWD/src/client/compositor.h \
   $$PWD/src/client/connection_thread.h \
   $$PWD/src/client/contrast.h \
   $$PWD/src/client/datadevice.h \
   $$PWD/src/client/datadevicemanager.h \
   $$PWD/src/client/dataoffer.h \
   $$PWD/src/client/datasource.h \
   $$PWD/src/client/dpms.h \
   $$PWD/src/client/event_queue.h \
   $$PWD/src/client/fakeinput.h \
   $$PWD/src/client/fullscreen_shell.h \
   $$PWD/src/client/idle.h \
   $$PWD/src/client/idleinhibit.h \
   $$PWD/src/client/keyboard.h \
   $$PWD/src/client/keystate.h \
   $$PWD/src/client/output.h \
   $$PWD/src/client/outputconfiguration.h \
   $$PWD/src/client/outputdevice.h \
   $$PWD/src/client/outputmanagement.h \
   $$PWD/src/client/plasmashell.h \
   $$PWD/src/client/plasmavirtualdesktop.h \
   $$PWD/src/client/plasmawindowmanagement.h \
   $$PWD/src/client/plasmawindowmodel.h \
   $$PWD/src/client/pointer.h \
   $$PWD/src/client/pointerconstraints.h \
   $$PWD/src/client/pointergestures.h \
   $$PWD/src/client/region.h \
   $$PWD/src/client/registry.h \
   $$PWD/src/client/relativepointer.h \
   $$PWD/src/client/remote_access.h \
   $$PWD/src/client/seat.h \
   $$PWD/src/client/server_decoration.h \
   $$PWD/src/client/server_decoration_palette.h \
   $$PWD/src/client/shadow.h \
   $$PWD/src/client/shell.h \
   $$PWD/src/client/shm_pool.h \
   $$PWD/src/client/slide.h \
   $$PWD/src/client/subcompositor.h \
   $$PWD/src/client/subsurface.h \
   $$PWD/src/client/surface.h \
   $$PWD/src/client/textinput.h \
   $$PWD/src/client/textinput_p.h \
   $$PWD/src/client/touch.h \
   $$PWD/src/client/wayland_pointer_p.h \
   $$PWD/src/client/xdgdecoration.h \
   $$PWD/src/client/xdgforeign.h \
   $$PWD/src/client/xdgforeign_p.h \
   $$PWD/src/client/xdgforeign_v2.h \
   $$PWD/src/client/xdgoutput.h \
   $$PWD/src/client/xdgshell.h \
   $$PWD/src/client/xdgshell_p.h \
   $$PWD/src/compat/wayland-xdg-shell-v5-client-protocol.h \
   $$PWD/src/compat/wayland-xdg-shell-v5-server-protocol.h \
   $$PWD/src/server/appmenu_interface.h \
   $$PWD/src/server/blur_interface.h \
   $$PWD/src/server/buffer_interface.h \
   $$PWD/src/server/clientconnection.h \
   $$PWD/src/server/compositor_interface.h \
   $$PWD/src/server/contrast_interface.h \
   $$PWD/src/server/datadevice_interface.h \
   $$PWD/src/server/datadevicemanager_interface.h \
   $$PWD/src/server/dataoffer_interface.h \
   $$PWD/src/server/dataoffer_interface_p.h \
   $$PWD/src/server/datasource_interface.h \
   $$PWD/src/server/display.h \
   $$PWD/src/server/dpms_interface.h \
   $$PWD/src/server/dpms_interface_p.h \
   $$PWD/src/server/drm_fourcc.h \
   $$PWD/src/server/eglstream_controller_interface.h \
   $$PWD/src/server/eglstream_controller_interface_p.h \
   $$PWD/src/server/fakeinput_interface.h \
   $$PWD/src/server/filtered_display.h \
   $$PWD/src/server/generic_shell_surface_p.h \
   $$PWD/src/server/global.h \
   $$PWD/src/server/global_p.h \
   $$PWD/src/server/idle_interface.h \
   $$PWD/src/server/idleinhibit_interface.h \
   $$PWD/src/server/idleinhibit_interface_p.h \
   $$PWD/src/server/keyboard_interface.h \
   $$PWD/src/server/keyboard_interface_p.h \
   $$PWD/src/server/keystate_interface.h \
   $$PWD/src/server/linuxdmabuf_v1_interface.h \
   $$PWD/src/server/output_interface.h \
   $$PWD/src/server/outputchangeset.h \
   $$PWD/src/server/outputchangeset_p.h \
   $$PWD/src/server/outputconfiguration_interface.h \
   $$PWD/src/server/outputdevice_interface.h \
   $$PWD/src/server/outputmanagement_interface.h \
   $$PWD/src/server/plasmashell_interface.h \
   $$PWD/src/server/plasmavirtualdesktop_interface.h \
   $$PWD/src/server/plasmawindowmanagement_interface.h \
   $$PWD/src/server/pointer_interface.h \
   $$PWD/src/server/pointer_interface_p.h \
   $$PWD/src/server/pointerconstraints_interface.h \
   $$PWD/src/server/pointerconstraints_interface_p.h \
   $$PWD/src/server/pointergestures_interface.h \
   $$PWD/src/server/pointergestures_interface_p.h \
   $$PWD/src/server/qtsurfaceextension_interface.h \
   $$PWD/src/server/region_interface.h \
   $$PWD/src/server/relativepointer_interface.h \
   $$PWD/src/server/relativepointer_interface_p.h \
   $$PWD/src/server/remote_access_interface.h \
   $$PWD/src/server/remote_access_interface_p.h \
   $$PWD/src/server/resource.h \
   $$PWD/src/server/resource_p.h \
   $$PWD/src/server/seat_interface.h \
   $$PWD/src/server/seat_interface_p.h \
   $$PWD/src/server/server_decoration_interface.h \
   $$PWD/src/server/server_decoration_palette_interface.h \
   $$PWD/src/server/shadow_interface.h \
   $$PWD/src/server/shell_interface.h \
   $$PWD/src/server/slide_interface.h \
   $$PWD/src/server/subcompositor_interface.h \
   $$PWD/src/server/subsurface_interface_p.h \
   $$PWD/src/server/surface_interface.h \
   $$PWD/src/server/surface_interface_p.h \
   $$PWD/src/server/surfacerole_p.h \
   $$PWD/src/server/tablet_interface.h \
   $$PWD/src/server/textinput_interface.h \
   $$PWD/src/server/textinput_interface_p.h \
   $$PWD/src/server/touch_interface.h \
   $$PWD/src/server/xdgdecoration_interface.h \
   $$PWD/src/server/xdgforeign_interface.h \
   $$PWD/src/server/xdgforeign_v2_interface_p.h \
   $$PWD/src/server/xdgoutput_interface.h \
   $$PWD/src/server/xdgshell_interface.h \
   $$PWD/src/server/xdgshell_interface_p.h \
   $$PWD/src/server/xdgshell_stable_interface_p.h \
   $$PWD/src/server/xdgshell_v5_interface_p.h \
   $$PWD/src/server/xdgshell_v6_interface_p.h \
   $$PWD/src/tools/testserver/testserver.h \
   $$PWD/src/tools/generator.h

SOURCES = \
   $$PWD/src/client/appmenu.cpp \
   $$PWD/src/client/blur.cpp \
   $$PWD/src/client/buffer.cpp \
   $$PWD/src/client/compositor.cpp \
   $$PWD/src/client/connection_thread.cpp \
   $$PWD/src/client/contrast.cpp \
   $$PWD/src/client/datadevice.cpp \
   $$PWD/src/client/datadevicemanager.cpp \
   $$PWD/src/client/dataoffer.cpp \
   $$PWD/src/client/datasource.cpp \
   $$PWD/src/client/dpms.cpp \
   $$PWD/src/client/event_queue.cpp \
   $$PWD/src/client/fakeinput.cpp \
   $$PWD/src/client/fullscreen_shell.cpp \
   $$PWD/src/client/idle.cpp \
   $$PWD/src/client/idleinhibit.cpp \
   $$PWD/src/client/keyboard.cpp \
   $$PWD/src/client/keystate.cpp \
   $$PWD/src/client/output.cpp \
   $$PWD/src/client/outputconfiguration.cpp \
   $$PWD/src/client/outputdevice.cpp \
   $$PWD/src/client/outputmanagement.cpp \
   $$PWD/src/client/plasmashell.cpp \
   $$PWD/src/client/plasmavirtualdesktop.cpp \
   $$PWD/src/client/plasmawindowmanagement.cpp \
   $$PWD/src/client/plasmawindowmodel.cpp \
   $$PWD/src/client/pointer.cpp \
   $$PWD/src/client/pointerconstraints.cpp \
   $$PWD/src/client/pointergestures.cpp \
   $$PWD/src/client/region.cpp \
   $$PWD/src/client/registry.cpp \
   $$PWD/src/client/relativepointer.cpp \
   $$PWD/src/client/remote_access.cpp \
   $$PWD/src/client/seat.cpp \
   $$PWD/src/client/server_decoration.cpp \
   $$PWD/src/client/server_decoration_palette.cpp \
   $$PWD/src/client/shadow.cpp \
   $$PWD/src/client/shell.cpp \
   $$PWD/src/client/shm_pool.cpp \
   $$PWD/src/client/slide.cpp \
   $$PWD/src/client/subcompositor.cpp \
   $$PWD/src/client/subsurface.cpp \
   $$PWD/src/client/surface.cpp \
   $$PWD/src/client/textinput.cpp \
   $$PWD/src/client/textinput_v0.cpp \
   $$PWD/src/client/textinput_v2.cpp \
   $$PWD/src/client/touch.cpp \
   $$PWD/src/client/xdgdecoration.cpp \
   $$PWD/src/client/xdgforeign.cpp \
   $$PWD/src/client/xdgforeign_v2.cpp \
   $$PWD/src/client/xdgoutput.cpp \
   $$PWD/src/client/xdgshell.cpp \
   $$PWD/src/client/xdgshell_stable.cpp \
   $$PWD/src/client/xdgshell_v5.cpp \
   $$PWD/src/client/xdgshell_v6.cpp \
   $$PWD/src/compat/wayland-xdg-shell-v5-protocol.c \
   $$PWD/src/server/appmenu_interface.cpp \
   $$PWD/src/server/blur_interface.cpp \
   $$PWD/src/server/buffer_interface.cpp \
   $$PWD/src/server/clientconnection.cpp \
   $$PWD/src/server/compositor_interface.cpp \
   $$PWD/src/server/contrast_interface.cpp \
   $$PWD/src/server/datadevice_interface.cpp \
   $$PWD/src/server/datadevicemanager_interface.cpp \
   $$PWD/src/server/dataoffer_interface.cpp \
   $$PWD/src/server/datasource_interface.cpp \
   $$PWD/src/server/display.cpp \
   $$PWD/src/server/dpms_interface.cpp \
   $$PWD/src/server/eglstream_controller_interface.cpp \
   $$PWD/src/server/fakeinput_interface.cpp \
   $$PWD/src/server/filtered_display.cpp \
   $$PWD/src/server/global.cpp \
   $$PWD/src/server/idle_interface.cpp \
   $$PWD/src/server/idleinhibit_interface.cpp \
   $$PWD/src/server/idleinhibit_interface_v1.cpp \
   $$PWD/src/server/keyboard_interface.cpp \
   $$PWD/src/server/keystate_interface.cpp \
   $$PWD/src/server/linuxdmabuf_v1_interface.cpp \
   $$PWD/src/server/output_interface.cpp \
   $$PWD/src/server/outputchangeset.cpp \
   $$PWD/src/server/outputconfiguration_interface.cpp \
   $$PWD/src/server/outputdevice_interface.cpp \
   $$PWD/src/server/outputmanagement_interface.cpp \
   $$PWD/src/server/plasmashell_interface.cpp \
   $$PWD/src/server/plasmavirtualdesktop_interface.cpp \
   $$PWD/src/server/plasmawindowmanagement_interface.cpp \
   $$PWD/src/server/pointer_interface.cpp \
   $$PWD/src/server/pointerconstraints_interface.cpp \
   $$PWD/src/server/pointerconstraints_interface_v1.cpp \
   $$PWD/src/server/pointergestures_interface.cpp \
   $$PWD/src/server/pointergestures_interface_v1.cpp \
   $$PWD/src/server/qtsurfaceextension_interface.cpp \
   $$PWD/src/server/region_interface.cpp \
   $$PWD/src/server/relativepointer_interface.cpp \
   $$PWD/src/server/relativepointer_interface_v1.cpp \
   $$PWD/src/server/remote_access_interface.cpp \
   $$PWD/src/server/resource.cpp \
   $$PWD/src/server/seat_interface.cpp \
   $$PWD/src/server/server_decoration_interface.cpp \
   $$PWD/src/server/server_decoration_palette_interface.cpp \
   $$PWD/src/server/shadow_interface.cpp \
   $$PWD/src/server/shell_interface.cpp \
   $$PWD/src/server/slide_interface.cpp \
   $$PWD/src/server/subcompositor_interface.cpp \
   $$PWD/src/server/surface_interface.cpp \
   $$PWD/src/server/surfacerole.cpp \
   $$PWD/src/server/tablet_interface.cpp \
   $$PWD/src/server/textinput_interface.cpp \
   $$PWD/src/server/textinput_interface_v0.cpp \
   $$PWD/src/server/textinput_interface_v2.cpp \
   $$PWD/src/server/touch_interface.cpp \
   $$PWD/src/server/xdgdecoration_interface.cpp \
   $$PWD/src/server/xdgforeign_interface.cpp \
   $$PWD/src/server/xdgforeign_v2_interface.cpp \
   $$PWD/src/server/xdgoutput_interface.cpp \
   $$PWD/src/server/xdgshell_interface.cpp \
   $$PWD/src/server/xdgshell_stable_interface.cpp \
   $$PWD/src/server/xdgshell_v5_interface.cpp \
   $$PWD/src/server/xdgshell_v6_interface.cpp \
   $$PWD/src/tools/testserver/main.cpp \
   $$PWD/src/tools/testserver/testserver.cpp \
   $$PWD/src/tools/generator.cpp

INCLUDEPATH = \
    $$PWD/autotests/client \
    $$PWD/src/client \
    $$PWD/src/compat \
    $$PWD/src/server \
    $$PWD/src/tools \
    $$PWD/src/tools/testserver \
    $$PWD/tests

#DEFINES = 

